version: "3.8"

services:
  mariadb:
    image: mariadb:11.4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - webnetz

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    ports:
      - "127.0.0.1:8081:80"
    networks:
      - webnetz

  apache:
    build: .
    restart: unless-stopped
    user: "33:33"
    volumes:
      - ./www:/var/www/html
    ports:
      - "127.0.0.1:8082:80"
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/apache2
    cap_drop:
      - ALL
    networks:
      - webnetz

networks:
  webnetz:
    driver: bridge